### ISSUE TITLE
Hint/indication of unsorted screenshots when launch the App

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#226]
1. Install ScreenshotGo
2. Launch ScreenshotGo
3. Tap Lets Load it
4. Tap Later
5. Tap system Back key
6. Tap ScreenshotGo again

Expected Result
 - Don't show "Unsorted screenshots"

Actual Result
 - Show "Unsorted screenshots"
 - Video: https://drive.google.com/open?id=1BjIZOpMPdl5pk2L3qNrycuzFeFlXtnV-

Reproduce Rate: 10/10

Device: Redmi 4A
Android 7.x
ScreenshotGO 1.0(387).nightly

**Comment by cynthiatang** [comment]
As the developer and UX discussed, it's a P2 issue.

**Comment by ChenMorpheus** [comment]
@chloechen1122 @weslyhuang Since we're adopting relatively aggressive onboardings, like spotlights, I revisited the previous spec and made some updates to prevent countless aggressive prompts. The implement effort is acceptable based on @pharspher's comment. I believed replacing the prompt of unsorted shots with a notification badge is worth to invest to streamline the experience of introducing new features.

Below is my proposal
<img width="1515" alt="image" src="https://user-images.githubusercontent.com/18019946/51027669-73186100-15cc-11e9-859b-1914ac02f5e8.png">

**Comment by ChenMorpheus** [comment]
Please find the attached link for visual spec.

<img width="1853" alt="image" src="https://user-images.githubusercontent.com/18019946/51594349-33883800-1f2f-11e9-8b32-75a5e4ab36ff.png">

https://mozilla.invisionapp.com/share/CQNB9INNKDX#/342492216_5-9_Unsorted_Badge

**Comment by weslyhuang** [comment]
should update title

**Comment by pharspher** [comment]
resolved in #623

**Comment by weslyhuang** [comment]
@ChenMorpheus @pharspher 

just to clarify, the hint badge will disappear when:
A. user enter then leave the "unsorted collection", OR
B. user enter then leave any collection?

**Comment by Conjuror** [comment]
To save the discussion in a closed issue, let's move to issue #632 to follow up.
