### ISSUE TITLE
 Text selected  & Web search(doesn't opened by default app)

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/ScreenshotGo#323]
**Describe the bug**
 Text selected  & Web search(doesn't opened by default app)

**Steps To Reproduce**
1. Launch ScreenshotGo
2. Tap a shot 
3. Tap OCR
4. Long press selects the text 
5. Tap WEB SEARCH or search icon 

**Expected behavior**
open  web search by default browser app
**Actual behavior**
open web search by mobile's default app

**Screenshots/videos**
https://drive.google.com/file/d/1wQcTXP25CRzFp80cxEp1dpEM9RG9Lmbs/view

**Device info (please complete the following information):**
- Device:Redmi 4X
- OS: Android: 7.1.2
- Version 1.0(505).nightly

**Comment by weslyhuang** [comment]
dup #178  to this one. which is with a Mi device also:

Redmi 4A
Android 7.1.2
Scryer 1.0(320).nightly

**Comment by weslyhuang** [comment]
@ChenMorpheus just to be sure, will this be covered in the new OCR flow?

**Comment by ChenMorpheus** [comment]
@weslyhuang Based on the previous conclusion, the current implementation directs users to find the default "search provider" instead of "default search engine opened in the default browser" since we haven't had any contract with any search engine. However, we might need to discuss a better solution to improve the usability of the new OCR flow. @chloechen1122 @joechengla What do you think?

Besides, I attached the current implementation of UX spec here since the spec on InVision is the new OCR flow.
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/18019946/47197380-7a96e800-d398-11e8-92da-16610737425a.png">

**Comment by weslyhuang** [comment]
the current design limitation. will be fixed by #448.

**Comment by witsmo** [comment]
Verify resolved on ScreenshootGo 1.0(767)
Device: Redmi 4A
OS: Android 7.1.2
