### ISSUE TITLE
[Google Play Feedback] Export screenshots to the gallery

### ISSUE THREAD

**Issue by chloechen1122** [mozilla-tw/ScreenshotGo#334]
User feedback from Google Play (Hanif Pandu S Oct 22, 2018 at 1:06 AM):
This app can hardly export screenshots to the gallery app.

Device: Galaxy E7 (e73g)
OS: Android 5.1

**Comment by weslyhuang** [comment]
guess could be a low priority feature-backlog, unless some new input indicating it's critical?

**Comment by weslyhuang** [comment]
should we consider it dup to #351?

**Comment by weslyhuang** [comment]
Two possible reasons, which are resolved respectively.
1. didn't immediately update gallery when our App took a screenshot (which is fixed by Max's patch), thus users believe they have the need to export the screenshots. 
2. really have a need to export their screenshots anyway, then this is the same as #351. (duplicate)
