### ISSUE TITLE
disable/enable toast not display properly

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/ScreenshotGo#425]
Step:
1. Launch screenshot 
2. tap menu -> settings
3. enable screenshot feature
4. disable screenshot feature 
5. repeat 3&4 multiple times

result:
toast not display properly

video:
https://drive.google.com/open?id=1JXwL_3t-Sr5T7wiT619WUGoDqr8d9vs5

device:
ScreenshotGo
Version 0.8(688)
Nexus 5 (6.0.1)

**Comment by weslyhuang** [comment]
1. don't seem to be a normal use case but would be interested to know if the "displayed status" will be permanently wrong in the end. 
2. and I assume the actual disable/enable status aligns the switch status always, otherwise would be a bit more serious) @ivantw08 would you help confirm above 2 things? tks.

**Comment by ivantw08** [comment]
@weslyhuang  After the unusual toast display. Everything work well if we tap the toggle normally.

**Comment by weslyhuang** [comment]
tks Ivan, then to me it's S2 & P2 at most.
