### ISSUE TITLE
Create query for usage ratio

### ISSUE THREAD

**Issue by chloechen1122** [mozilla-tw/ScreenshotGo#430]
To track the ratio of using ScreenshotGo to capture screen versus other screenshot tools.

**Comment by weslyhuang** [comment]
need to discuss with Eddie about how/what to track, before working on it.

**Comment by elin-moco** [comment]
@weslyhuang had some discussion with @benjamin-cheng 
there's no actions we can take on dev side since we've already got what we can track (capture via external/FAB/notification)
The only thing we can do is to come up with a more precise query on telemetry for this.

**Comment by weslyhuang** [comment]
removed from Sprint#2 per comment above.

**Comment by elin-moco** [comment]
@chloechen1122 
Here is the ratio for ScreenshotGo DAU:
https://sql.telemetry.mozilla.org/queries/60171#156263

I can get this chart for another segment (who used "external", which means other apps or hardware key)
So it may be closer to general public instead of loyal user.
Will update here once done.

**Comment by chloechen1122** [comment]
Well noted with thanks. Let's keep an eye on this.

**Comment by elin-moco** [comment]
Ratio chart with "external" user segment
https://sql.telemetry.mozilla.org/queries/60570#156342
