### ISSUE TITLE
Add thumbnail for "new screenshot captured" notification

### ISSUE THREAD

**Issue by chloechen1122** [mozilla-tw/ScreenshotGo#492]
The notifications of "New Screenshot Captured" & "Tap to take screenshot " are similar, and could be mistaken for each other. Perhaps we could add a thumbnail on the "new screenshot captured" notice.

![screenshot_20190108-122433](https://user-images.githubusercontent.com/43133942/50812164-97fea100-134c-11e9-81e2-23e548885f3f.png)

**Comment by ChenMorpheus** [comment]
@chloechen1122 I totally understand your concern, and that was what we discovered from the usability testing. However, we had the design already, but we didn't have time and resource to make the desired design happen. The current design was the least effort, but it's ready to implement since the UX spec is there. 

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/18019946/50815566-891deb80-1358-11e9-934d-345851608f48.png">

Spec link:
http://mozilla.invisionapp.com/share/24N3MMQB986#/310133910_1-2_Add_To_Collection_With_Hardware_Key

**Comment by weslyhuang** [comment]
update the subject for quick understanding.
