### ISSUE TITLE
When tap the area outside of the keyboard in search mode, keyboard still display

### ISSUE THREAD

**Issue by witsmo** [mozilla-tw/ScreenshotGo#609]
Describe the bug
When tap the area outside of the keyboard in search mode, keyboard still display

Steps To Reproduce
1. Tap the [search bar]
2. Type [a letter]
3. Tap the area [outside] of the [keyboard]

Expected behavior
Dismis [keyboard]

Actual behavior
keyboard still display

Screenshots/videos
https://drive.google.com/file/d/1MwrNxk7S0GBFiZ3r-agDPUcA22-5trfM/view?usp=sharing

Device info (please complete the following information):
Device: Advan i5C
OS: Android 5.1
Version: Version 1.0(1102).nightly

**Comment by weslyhuang** [comment]
usability related, seems more than P2 but unsure about P1, maybe @ChenMorpheus can help comment? tks.

**Comment by ChenMorpheus** [comment]
From the UX perspective, the intention to tap outside of keyboard means users want to have interactions with the results, so dismissing keyboard could expand the viewport for users to easily explore and spot results. As a result, I highly suggest fixing this bug since most search-related features in Google apps dismiss keyboard as well when tapping outside of the keyboard area. However, we could discuss the priority considering the timeline and feasibility.

**Comment by weslyhuang** [comment]
thanks, it's P1 or even higher then.

**Comment by weslyhuang** [comment]
P0 as Sprint#7's nice to have.
