### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by rugk** [mozilla-tw/ScreenshotGo#643]
Could you possibly publish it on https://f-droid.org/? As a FLOSS app, this is the perfect place to be.

Firefox Rocket (Firefox Lite) and Firefox Focus are already on F-Droid. See https://github.com/mozilla-tw/FirefoxLite/issues/1050 and https://github.com/mozilla-mobile/focus-android/issues/617.

**Comment by weslyhuang** [comment]
per the history of Lite https://github.com/mozilla-tw/FirefoxLite/issues/1050 the relevant tasks seem to be:

1. check if we have any non-free dependencies (I think we have)
2. remove those in the build to be published on F-droid
3. check for legal approval

Since we are moving dev. resource to the other project I'm not sure if this will be the priority, @chloechen1122 how do you think?

**Comment by chloechen1122** [comment]
Lite team will talk with Mika first, and we'll follow their example. Thanks for the heads up!
